export const SET_AUTHED_USER = 'SET_AUTHED_USER'

export const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS'
export const ADD_QUESTION = 'ADD_QUESTION'
export const ADD_QUESTION_ANSWER = 'ADD_QUESTION_ANSWER'
export const REMOVE_QUESTION_ANSWER = 'REMOVE_QUESTION_ANSWER'

export const RECEIVE_USERS = 'RECEIVE_USERS'
export const ADD_QUESTION_TO_USER = 'ADD_QUESTION_TO_USER'
export const ADD_ANSWER_TO_USER = 'ADD_ANSWER_TO_USER'
export const ADD_USER = 'ADD_USER'
export const REMOVE_ANSWER_FROM_USER = 'REMOVE_ANSWER_FROM_USER'